name: Build sample

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md', '**.MD' ]
    tags-ignore:
      - '**'
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md', '**.MD' ]
  workflow_dispatch:

concurrency:
  group: 'ci-${{ github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx2G -Dorg.gradle.daemon=false -Dkotlin.incremental=false -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  android:
    strategy:
      matrix:
        os: [ macos-11, macos-12, macos-13 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/cache
            ~/.konan/dependencies
            ~/.konan/kotlin-native-macos*
            ~/.konan/kotlin-native-mingw*
            ~/.konan/kotlin-native-windows*
            ~/.konan/kotlin-native-linux*
            ~/.konan/kotlin-native-prebuilt-macos*
            ~/.konan/kotlin-native-prebuilt-mingw*
            ~/.konan/kotlin-native-prebuilt-windows*
            ~/.konan/kotlin-native-prebuilt-linux*
          key: ${{ matrix.os }}-konan-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ matrix.os }}-konan-
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew :sample:app:assembleDebug --stacktrace --info

      - name: Check for JVM crash logs
        if: failure()
        run: |
          mkdir -p crash_logs
          find . -name 'hs_err_pid*.log' -exec mv {} crash_logs/ \;
          if [ -n "$(ls -A crash_logs)" ]; then
            echo "JVM crash logs found."
          else
            echo "No JVM crash logs found."
          fi

      - name: Upload JVM crash logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jvm-crash-logs
          path: crash_logs/
